### ISSUE TITLE
Won't compile on newest PhysFS

### ISSUE THREAD

**Issue by vinyldarkscratch** [elizagamedev/mkxp-oneshot#14]
Since PhysFS 3.0.0 came out (September 27th), the engine won't compile any longer, without a few changes.  Take a look at: https://github.com/Ancurio/mkxp/pull/174

**Comment by KockaAdmiralac** [comment]
For anybody wanting to temporarily compile the engine before this issue is solved, using `hg checkout f910eacfda41` after cloning PhysFS repo from Mercurial worked for me. I've had an issue with PhysFS a little before 3.0 though.

**Comment by vinyldarkscratch** [comment]
This issue is fixed in the [SyngleChance](https://github.com/vinyldarkscratch/synglechance) fork, and will be fixed in here once it's all ready to be merged.  :wink:
